### ISSUE TITLE
Баги 1 версии

### ISSUE THREAD

**Issue by Yandex-an** [Flying-Ghost-Marlin/Marlin#2]
1. SD карта монтируется только при включении принтера.
2. Не работает Wi-Fi
3. Загрузка и выгрузка филамента из меню сменить филамент.
4. Только если на экструдетре установлен драйвер TMC2208 при включенном Linear advance через некоторое время происходит его отключения из за перегрузки. нужно настроить K фактор.

**Comment by TheDemonCat** [comment]
@Yandex-an я разбил баги на отдельные ишузы. Этот закрываю.
